site_name: FS Data Model
theme:
  name: material
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Data model:
    - Diagram: model/model_diagram.md
    - Glossary: model/glossary.md
    - Indicator dimensions: dimensions_table.md
  - Indicator definitions: indicators_table.md
  - Indicator data collection details: indicator_data_collection_details_table.md
  - Indicator databases: databases_table.md
  - Indicator selection details:
    - Indicator criterion categories: model/CriterionCategory.md
    - Indicator criteria: indicator_criteria_table.md
    - Indicator scores: indicator_scores.md
docs_dir: docs
site_url: https://biometris.github.io/FS-Datamodel
repo_url: https://github.com/biometris/FS-Datamodel
extra_css:
  - style.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/echarts@6.0.0/dist/echarts.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js
